repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '^\.flox/'
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: flox activate -- gofmt -w
        language: system
        types: [go]
        exclude: '_templ\.go$'

      - id: go-imports
        name: go imports
        entry: flox activate -- goimports -w
        language: system
        types: [go]
        exclude: '_templ\.go$'

      - id: go-vet
        name: go vet
        entry: flox activate -- go vet ./...
        language: system
        types: [go]
        pass_filenames: false

      - id: templ-fmt
        name: templ fmt
        entry: flox activate -- templ fmt .
        language: system
        pass_filenames: false
        types: [file]
        files: '\.templ$'

      - id: templ-generate
        name: templ generate
        entry: flox activate -- templ generate
        language: system
        pass_filenames: false
        types: [file]
        files: '\.templ$'

      - id: go-test
        name: go test
        entry: flox activate -- go test ./...
        language: system
        pass_filenames: false
        stages: [pre-push]
